/*
 *
 *  Licensed to the Apache Software Foundation (ASF) under one
 *  or more contributor license agreements.  See the NOTICE file
 *  distributed with this work for additional information
 *  regarding copyright ownership.  The ASF licenses this file
 *  to you under the Apache License, Version 2.0 (the
 *  "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at
 *       http://www.apache.org/licenses/LICENSE-2.0
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */

/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package graphene.model.idl;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum G_CanonicalPropertyType { 
  ACCOUNT, ACCOUNT_CLASS, ACCOUNT_TYPE, REPORT_ID, ADDRESS, ADDRESS_CITY, ADDRESS_STREET, ADDRESS_BLDG, ADDRESS_POSTAL_CODE, ADDRESS_COUNTY, ADDRESS_STATE_PROVINCE, ADDRESS_COUNTRY, ADDRESS_OTHER, GEO, EXPORTADDRESS, IMPORTADDRESS, ANY, COMBO, CONFIRMED, CONTEXT, CORPORATE_CUSTOMER, CURRENCY, CUSTOMER_CLASS, CUSTOMER_NUMBER, CUSTOMER_TYPE, DECEASED, DESCRIPTION, EMAIL_ADDRESS, IP, DEVICE_ID, SERIAL_NUMBER, FAMILYROLE, OTHER_ID, IMPORTANCE, JSONVALUE, LINK, METRIC_CERTAINTY, METRIC_IMPUTED, METRIC_IMPUTEDFROM, METRIC_PROVENANCE, METRIC_SCORE, MEDIA, NAME, NODETYPE, OCCUPATION, OTHER, PAYLOAD, NGRAM, PASSPORT, TAXID, EIN, SSN, GOVERNMENTID, VISA, LICENSEPLATE, VIN, FLIGHT, PHONE, PROVIDER_COMPANY_NAME, PROVIDER_INDUSTRY, SEX, SYSTEMNAME, TIME_CLOSING_DATE, TIME_DATE, TIME_DAY, TIME_HOUR, TIME_MONTH, TIME_OPENING_DATE, TIME_YEAR, VALUE, VIP, WALLET_ADDRESS, USERNAME, ENTITY, TYPE, URL, SUBJECT, FREETEXT, INSTITUTION, FILER, EVENT, REDACTED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"G_CanonicalPropertyType\",\"namespace\":\"graphene.model.idl\",\"symbols\":[\"ACCOUNT\",\"ACCOUNT_CLASS\",\"ACCOUNT_TYPE\",\"REPORT_ID\",\"ADDRESS\",\"ADDRESS_CITY\",\"ADDRESS_STREET\",\"ADDRESS_BLDG\",\"ADDRESS_POSTAL_CODE\",\"ADDRESS_COUNTY\",\"ADDRESS_STATE_PROVINCE\",\"ADDRESS_COUNTRY\",\"ADDRESS_OTHER\",\"GEO\",\"EXPORTADDRESS\",\"IMPORTADDRESS\",\"ANY\",\"COMBO\",\"CONFIRMED\",\"CONTEXT\",\"CORPORATE_CUSTOMER\",\"CURRENCY\",\"CUSTOMER_CLASS\",\"CUSTOMER_NUMBER\",\"CUSTOMER_TYPE\",\"DECEASED\",\"DESCRIPTION\",\"EMAIL_ADDRESS\",\"IP\",\"DEVICE_ID\",\"SERIAL_NUMBER\",\"FAMILYROLE\",\"OTHER_ID\",\"IMPORTANCE\",\"JSONVALUE\",\"LINK\",\"METRIC_CERTAINTY\",\"METRIC_IMPUTED\",\"METRIC_IMPUTEDFROM\",\"METRIC_PROVENANCE\",\"METRIC_SCORE\",\"MEDIA\",\"NAME\",\"NODETYPE\",\"OCCUPATION\",\"OTHER\",\"PAYLOAD\",\"NGRAM\",\"PASSPORT\",\"TAXID\",\"EIN\",\"SSN\",\"GOVERNMENTID\",\"VISA\",\"LICENSEPLATE\",\"VIN\",\"FLIGHT\",\"PHONE\",\"PROVIDER_COMPANY_NAME\",\"PROVIDER_INDUSTRY\",\"SEX\",\"SYSTEMNAME\",\"TIME_CLOSING_DATE\",\"TIME_DATE\",\"TIME_DAY\",\"TIME_HOUR\",\"TIME_MONTH\",\"TIME_OPENING_DATE\",\"TIME_YEAR\",\"VALUE\",\"VIP\",\"WALLET_ADDRESS\",\"USERNAME\",\"ENTITY\",\"TYPE\",\"URL\",\"SUBJECT\",\"FREETEXT\",\"INSTITUTION\",\"FILER\",\"EVENT\",\"REDACTED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
