/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package graphene.model.idl;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum G_CanonicalTruthValues { 
  TRUE, FALSE, UNKNOWN, UNCERTAIN, REDACTED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"G_CanonicalTruthValues\",\"namespace\":\"graphene.model.idl\",\"symbols\":[\"TRUE\",\"FALSE\",\"UNKNOWN\",\"UNCERTAIN\",\"REDACTED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
