/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package graphene.model.idl;  
@SuppressWarnings("all")
/** This is the current list of tags for Entities:
	 
	 CHANGED in 1.6:
	   - added ACCOUNT_OWNER, CLUSTER_SUMMARY */
@org.apache.avro.specific.AvroGenerated
public enum G_EntityTag { 
  ACCOUNT_OWNER, ACCOUNT, GROUP, CLUSTER, CLUSTER_SUMMARY, FILE, ANONYMOUS, PROMPT_FOR_DETAILS, OTHER  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"G_EntityTag\",\"namespace\":\"graphene.model.idl\",\"doc\":\"This is the current list of tags for Entities:\\n\\t \\n\\t CHANGED in 1.6:\\n\\t   - added ACCOUNT_OWNER, CLUSTER_SUMMARY\",\"symbols\":[\"ACCOUNT_OWNER\",\"ACCOUNT\",\"GROUP\",\"CLUSTER\",\"CLUSTER_SUMMARY\",\"FILE\",\"ANONYMOUS\",\"PROMPT_FOR_DETAILS\",\"OTHER\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
