/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package graphene.model.idl;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum G_GroupFields { 
  id, name, description  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"G_GroupFields\",\"namespace\":\"graphene.model.idl\",\"symbols\":[\"id\",\"name\",\"description\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
