/*
 *
 *  Licensed to the Apache Software Foundation (ASF) under one
 *  or more contributor license agreements.  See the NOTICE file
 *  distributed with this work for additional information
 *  regarding copyright ownership.  The ASF licenses this file
 *  to you under the Apache License, Version 2.0 (the
 *  "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at
 *       http://www.apache.org/licenses/LICENSE-2.0
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */

/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package graphene.model.idl;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class G_GraphViewEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"G_GraphViewEvent\",\"namespace\":\"graphene.model.idl\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"default\":null},{\"name\":\"reportId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"reportType\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"reportPageLink\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"timeInitiated\",\"type\":\"long\"},{\"name\":\"userId\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"],\"default\":\"None\"},{\"name\":\"userName\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"],\"default\":\"None\"},{\"name\":\"queryObject\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\",\"java-class\":\"mil.darpa.vande.generic.V_GraphQuery\"},\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
   private java.lang.String id;
   private java.lang.String reportId;
   private java.lang.String reportType;
   private java.lang.String reportPageLink;
   private long timeInitiated;
   private java.lang.String userId;
   private java.lang.String userName;
   private mil.darpa.vande.generic.V_GraphQuery queryObject;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public G_GraphViewEvent() {}

  /**
   * All-args constructor.
   */
  public G_GraphViewEvent(java.lang.String id, java.lang.String reportId, java.lang.String reportType, java.lang.String reportPageLink, java.lang.Long timeInitiated, java.lang.String userId, java.lang.String userName, mil.darpa.vande.generic.V_GraphQuery queryObject) {
    this.id = id;
    this.reportId = reportId;
    this.reportType = reportType;
    this.reportPageLink = reportPageLink;
    this.timeInitiated = timeInitiated;
    this.userId = userId;
    this.userName = userName;
    this.queryObject = queryObject;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return reportId;
    case 2: return reportType;
    case 3: return reportPageLink;
    case 4: return timeInitiated;
    case 5: return userId;
    case 6: return userName;
    case 7: return queryObject;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.String)value$; break;
    case 1: reportId = (java.lang.String)value$; break;
    case 2: reportType = (java.lang.String)value$; break;
    case 3: reportPageLink = (java.lang.String)value$; break;
    case 4: timeInitiated = (java.lang.Long)value$; break;
    case 5: userId = (java.lang.String)value$; break;
    case 6: userName = (java.lang.String)value$; break;
    case 7: queryObject = (mil.darpa.vande.generic.V_GraphQuery)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'reportId' field.
   */
  public java.lang.String getReportId() {
    return reportId;
  }

  /**
   * Sets the value of the 'reportId' field.
   * @param value the value to set.
   */
  public void setReportId(java.lang.String value) {
    this.reportId = value;
  }

  /**
   * Gets the value of the 'reportType' field.
   */
  public java.lang.String getReportType() {
    return reportType;
  }

  /**
   * Sets the value of the 'reportType' field.
   * @param value the value to set.
   */
  public void setReportType(java.lang.String value) {
    this.reportType = value;
  }

  /**
   * Gets the value of the 'reportPageLink' field.
   */
  public java.lang.String getReportPageLink() {
    return reportPageLink;
  }

  /**
   * Sets the value of the 'reportPageLink' field.
   * @param value the value to set.
   */
  public void setReportPageLink(java.lang.String value) {
    this.reportPageLink = value;
  }

  /**
   * Gets the value of the 'timeInitiated' field.
   */
  public java.lang.Long getTimeInitiated() {
    return timeInitiated;
  }

  /**
   * Sets the value of the 'timeInitiated' field.
   * @param value the value to set.
   */
  public void setTimeInitiated(java.lang.Long value) {
    this.timeInitiated = value;
  }

  /**
   * Gets the value of the 'userId' field.
   */
  public java.lang.String getUserId() {
    return userId;
  }

  /**
   * Sets the value of the 'userId' field.
   * @param value the value to set.
   */
  public void setUserId(java.lang.String value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'userName' field.
   */
  public java.lang.String getUserName() {
    return userName;
  }

  /**
   * Sets the value of the 'userName' field.
   * @param value the value to set.
   */
  public void setUserName(java.lang.String value) {
    this.userName = value;
  }

  /**
   * Gets the value of the 'queryObject' field.
   */
  public mil.darpa.vande.generic.V_GraphQuery getQueryObject() {
    return queryObject;
  }

  /**
   * Sets the value of the 'queryObject' field.
   * @param value the value to set.
   */
  public void setQueryObject(mil.darpa.vande.generic.V_GraphQuery value) {
    this.queryObject = value;
  }

  /** Creates a new G_GraphViewEvent RecordBuilder */
  public static graphene.model.idl.G_GraphViewEvent.Builder newBuilder() {
    return new graphene.model.idl.G_GraphViewEvent.Builder();
  }
  
  /** Creates a new G_GraphViewEvent RecordBuilder by copying an existing Builder */
  public static graphene.model.idl.G_GraphViewEvent.Builder newBuilder(graphene.model.idl.G_GraphViewEvent.Builder other) {
    return new graphene.model.idl.G_GraphViewEvent.Builder(other);
  }
  
  /** Creates a new G_GraphViewEvent RecordBuilder by copying an existing G_GraphViewEvent instance */
  public static graphene.model.idl.G_GraphViewEvent.Builder newBuilder(graphene.model.idl.G_GraphViewEvent other) {
    return new graphene.model.idl.G_GraphViewEvent.Builder(other);
  }
  
  /**
   * RecordBuilder for G_GraphViewEvent instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<G_GraphViewEvent>
    implements org.apache.avro.data.RecordBuilder<G_GraphViewEvent> {

    private java.lang.String id;
    private java.lang.String reportId;
    private java.lang.String reportType;
    private java.lang.String reportPageLink;
    private long timeInitiated;
    private java.lang.String userId;
    private java.lang.String userName;
    private mil.darpa.vande.generic.V_GraphQuery queryObject;

    /** Creates a new Builder */
    private Builder() {
      super(graphene.model.idl.G_GraphViewEvent.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(graphene.model.idl.G_GraphViewEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.reportId)) {
        this.reportId = data().deepCopy(fields()[1].schema(), other.reportId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.reportType)) {
        this.reportType = data().deepCopy(fields()[2].schema(), other.reportType);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.reportPageLink)) {
        this.reportPageLink = data().deepCopy(fields()[3].schema(), other.reportPageLink);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.timeInitiated)) {
        this.timeInitiated = data().deepCopy(fields()[4].schema(), other.timeInitiated);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.userId)) {
        this.userId = data().deepCopy(fields()[5].schema(), other.userId);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.userName)) {
        this.userName = data().deepCopy(fields()[6].schema(), other.userName);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.queryObject)) {
        this.queryObject = data().deepCopy(fields()[7].schema(), other.queryObject);
        fieldSetFlags()[7] = true;
      }
    }
    
    /** Creates a Builder by copying an existing G_GraphViewEvent instance */
    private Builder(graphene.model.idl.G_GraphViewEvent other) {
            super(graphene.model.idl.G_GraphViewEvent.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.reportId)) {
        this.reportId = data().deepCopy(fields()[1].schema(), other.reportId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.reportType)) {
        this.reportType = data().deepCopy(fields()[2].schema(), other.reportType);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.reportPageLink)) {
        this.reportPageLink = data().deepCopy(fields()[3].schema(), other.reportPageLink);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.timeInitiated)) {
        this.timeInitiated = data().deepCopy(fields()[4].schema(), other.timeInitiated);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.userId)) {
        this.userId = data().deepCopy(fields()[5].schema(), other.userId);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.userName)) {
        this.userName = data().deepCopy(fields()[6].schema(), other.userName);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.queryObject)) {
        this.queryObject = data().deepCopy(fields()[7].schema(), other.queryObject);
        fieldSetFlags()[7] = true;
      }
    }

    /** Gets the value of the 'id' field */
    public java.lang.String getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public graphene.model.idl.G_GraphViewEvent.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'id' field */
    public graphene.model.idl.G_GraphViewEvent.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'reportId' field */
    public java.lang.String getReportId() {
      return reportId;
    }
    
    /** Sets the value of the 'reportId' field */
    public graphene.model.idl.G_GraphViewEvent.Builder setReportId(java.lang.String value) {
      validate(fields()[1], value);
      this.reportId = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'reportId' field has been set */
    public boolean hasReportId() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'reportId' field */
    public graphene.model.idl.G_GraphViewEvent.Builder clearReportId() {
      reportId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'reportType' field */
    public java.lang.String getReportType() {
      return reportType;
    }
    
    /** Sets the value of the 'reportType' field */
    public graphene.model.idl.G_GraphViewEvent.Builder setReportType(java.lang.String value) {
      validate(fields()[2], value);
      this.reportType = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'reportType' field has been set */
    public boolean hasReportType() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'reportType' field */
    public graphene.model.idl.G_GraphViewEvent.Builder clearReportType() {
      reportType = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'reportPageLink' field */
    public java.lang.String getReportPageLink() {
      return reportPageLink;
    }
    
    /** Sets the value of the 'reportPageLink' field */
    public graphene.model.idl.G_GraphViewEvent.Builder setReportPageLink(java.lang.String value) {
      validate(fields()[3], value);
      this.reportPageLink = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'reportPageLink' field has been set */
    public boolean hasReportPageLink() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'reportPageLink' field */
    public graphene.model.idl.G_GraphViewEvent.Builder clearReportPageLink() {
      reportPageLink = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'timeInitiated' field */
    public java.lang.Long getTimeInitiated() {
      return timeInitiated;
    }
    
    /** Sets the value of the 'timeInitiated' field */
    public graphene.model.idl.G_GraphViewEvent.Builder setTimeInitiated(long value) {
      validate(fields()[4], value);
      this.timeInitiated = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'timeInitiated' field has been set */
    public boolean hasTimeInitiated() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'timeInitiated' field */
    public graphene.model.idl.G_GraphViewEvent.Builder clearTimeInitiated() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'userId' field */
    public java.lang.String getUserId() {
      return userId;
    }
    
    /** Sets the value of the 'userId' field */
    public graphene.model.idl.G_GraphViewEvent.Builder setUserId(java.lang.String value) {
      validate(fields()[5], value);
      this.userId = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'userId' field has been set */
    public boolean hasUserId() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'userId' field */
    public graphene.model.idl.G_GraphViewEvent.Builder clearUserId() {
      userId = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'userName' field */
    public java.lang.String getUserName() {
      return userName;
    }
    
    /** Sets the value of the 'userName' field */
    public graphene.model.idl.G_GraphViewEvent.Builder setUserName(java.lang.String value) {
      validate(fields()[6], value);
      this.userName = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'userName' field has been set */
    public boolean hasUserName() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'userName' field */
    public graphene.model.idl.G_GraphViewEvent.Builder clearUserName() {
      userName = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'queryObject' field */
    public mil.darpa.vande.generic.V_GraphQuery getQueryObject() {
      return queryObject;
    }
    
    /** Sets the value of the 'queryObject' field */
    public graphene.model.idl.G_GraphViewEvent.Builder setQueryObject(mil.darpa.vande.generic.V_GraphQuery value) {
      validate(fields()[7], value);
      this.queryObject = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'queryObject' field has been set */
    public boolean hasQueryObject() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'queryObject' field */
    public graphene.model.idl.G_GraphViewEvent.Builder clearQueryObject() {
      queryObject = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    public G_GraphViewEvent build() {
      try {
        G_GraphViewEvent record = new G_GraphViewEvent();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.reportId = fieldSetFlags()[1] ? this.reportId : (java.lang.String) defaultValue(fields()[1]);
        record.reportType = fieldSetFlags()[2] ? this.reportType : (java.lang.String) defaultValue(fields()[2]);
        record.reportPageLink = fieldSetFlags()[3] ? this.reportPageLink : (java.lang.String) defaultValue(fields()[3]);
        record.timeInitiated = fieldSetFlags()[4] ? this.timeInitiated : (java.lang.Long) defaultValue(fields()[4]);
        record.userId = fieldSetFlags()[5] ? this.userId : (java.lang.String) defaultValue(fields()[5]);
        record.userName = fieldSetFlags()[6] ? this.userName : (java.lang.String) defaultValue(fields()[6]);
        record.queryObject = fieldSetFlags()[7] ? this.queryObject : (mil.darpa.vande.generic.V_GraphQuery) defaultValue(fields()[7]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
