/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package graphene.model.idl;  
@SuppressWarnings("all")
/** Amount of detail requested
	 
	 ADDED IN 1.6 */
@org.apache.avro.specific.AvroGenerated
public enum G_LevelOfDetail { 
  SUMMARY, FULL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"G_LevelOfDetail\",\"namespace\":\"graphene.model.idl\",\"doc\":\"Amount of detail requested\\n\\t \\n\\t ADDED IN 1.6\",\"symbols\":[\"SUMMARY\",\"FULL\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
