/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package graphene.model.idl;  
@SuppressWarnings("all")
/** * In addition to PropertyTags, a PropertyMatchDescriptor might also be one of these.

	 	ADDED IN 1.5 */
@org.apache.avro.specific.AvroGenerated
public enum G_PathMatchTag { 
  PATH_LENGTH, PATH_TIME, PATH_SOURCES, PATH_DESTS  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"G_PathMatchTag\",\"namespace\":\"graphene.model.idl\",\"doc\":\"* In addition to PropertyTags, a PropertyMatchDescriptor might also be one of these.\\n\\n\\t \\tADDED IN 1.5\",\"symbols\":[\"PATH_LENGTH\",\"PATH_TIME\",\"PATH_SOURCES\",\"PATH_DESTS\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
