package graphene.model.idl;

import graphene.model.idhelper.PropertyHelper;

public class G_SearchTuple<T> {
	protected G_SearchType searchType;
	protected G_CanonicalPropertyType family;
	private String specificPropertyType;

	/**
	 * @return the specificPropertyType
	 */
	public final String getSpecificPropertyType() {
		return specificPropertyType;
	}

	/**
	 * @param specificPropertyType
	 *            the specificPropertyType to set
	 */
	public final void setSpecificPropertyType(String specificPropertyType) {
		this.specificPropertyType = specificPropertyType;
	}

	protected T value;

	/**
	 * @return the family
	 */
	public G_CanonicalPropertyType getFamily() {
		return family;
	}

	/**
	 * @param family
	 *            the family to set
	 */
	public final void setFamily(G_CanonicalPropertyType family) {
		this.family = family;
	}

	/**
	 * Default constructor for when we are building from scratch.
	 */
	public G_SearchTuple() {
		// TODO Auto-generated constructor stub
	}

	public G_SearchTuple(T value, G_SearchType searchType) {
		this.value = value;
		this.searchType = searchType;
	}

	/**
	 * Helper constructor. Note that if this class ends up being generated by
	 * Avro, we may need to put helper constructors like this in a helper class
	 * that extends this one @see {@link PropertyHelper}
	 * 
	 * @param searchType
	 * @param family
	 * @param specificPropertyType
	 * @param value
	 */
	public G_SearchTuple(G_SearchType searchType,
			G_CanonicalPropertyType family, String specificPropertyType, T value) {
		super();
		this.searchType = searchType;
		this.family = family;
		this.specificPropertyType = specificPropertyType;
		this.value = value;
	}

	/**
	 * Helper constructor
	 * 
	 * @param searchType
	 * @param family
	 * @param value
	 */
	public G_SearchTuple(G_SearchType searchType,
			G_CanonicalPropertyType family, T value) {
		super();
		this.searchType = searchType;
		this.family = family;
		this.specificPropertyType = null;
		this.value = value;
	}

	public G_SearchType getSearchType() {
		return searchType;
	}

	public T getValue() {
		return value;
	}

	public void setSearchType(G_SearchType searchType) {
		this.searchType = searchType;
	}

	public void setValue(T value) {
		this.value = value;
	}

	@Override
	public String toString() {
		return "G_SearchTuple ["
				+ (searchType != null ? "searchType=" + searchType + ", " : "")
				+ (value != null ? "value=" + value : "") + "]";
	}
}
