/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package graphene.model.idl;  
@SuppressWarnings("all")
/** Sort type for temporal data with a numeric payload */
@org.apache.avro.specific.AvroGenerated
public enum G_SortBy { 
  DATE, AMOUNT  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"G_SortBy\",\"namespace\":\"graphene.model.idl\",\"doc\":\"Sort type for temporal data with a numeric payload\",\"symbols\":[\"DATE\",\"AMOUNT\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
