/*
 *
 *  Licensed to the Apache Software Foundation (ASF) under one
 *  or more contributor license agreements.  See the NOTICE file
 *  distributed with this work for additional information
 *  regarding copyright ownership.  The ASF licenses this file
 *  to you under the Apache License, Version 2.0 (the
 *  "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at
 *       http://www.apache.org/licenses/LICENSE-2.0
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */

/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package graphene.model.idl;  
@SuppressWarnings("all")
/** * Sort Criterion
	 * */
@org.apache.avro.specific.AvroGenerated
public class G_SortCriterion extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"G_SortCriterion\",\"namespace\":\"graphene.model.idl\",\"doc\":\"* Sort Criterion\\r\\n\\t *\",\"fields\":[{\"name\":\"sortDirection\",\"type\":{\"type\":\"enum\",\"name\":\"G_SortOrder\",\"doc\":\"* Sort orders\\r\\n\\t *\",\"symbols\":[\"ASC\",\"DESC\",\"UNSORTED\"]},\"doc\":\"the order of the sorting\"},{\"name\":\"propertyName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"* the name of the property we are sorting on\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** the order of the sorting */
   private graphene.model.idl.G_SortOrder sortDirection;
  /** * the name of the property we are sorting on */
   private java.lang.String propertyName;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public G_SortCriterion() {}

  /**
   * All-args constructor.
   */
  public G_SortCriterion(graphene.model.idl.G_SortOrder sortDirection, java.lang.String propertyName) {
    this.sortDirection = sortDirection;
    this.propertyName = propertyName;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return sortDirection;
    case 1: return propertyName;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: sortDirection = (graphene.model.idl.G_SortOrder)value$; break;
    case 1: propertyName = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'sortDirection' field.
   * the order of the sorting   */
  public graphene.model.idl.G_SortOrder getSortDirection() {
    return sortDirection;
  }

  /**
   * Sets the value of the 'sortDirection' field.
   * the order of the sorting   * @param value the value to set.
   */
  public void setSortDirection(graphene.model.idl.G_SortOrder value) {
    this.sortDirection = value;
  }

  /**
   * Gets the value of the 'propertyName' field.
   * * the name of the property we are sorting on   */
  public java.lang.String getPropertyName() {
    return propertyName;
  }

  /**
   * Sets the value of the 'propertyName' field.
   * * the name of the property we are sorting on   * @param value the value to set.
   */
  public void setPropertyName(java.lang.String value) {
    this.propertyName = value;
  }

  /** Creates a new G_SortCriterion RecordBuilder */
  public static graphene.model.idl.G_SortCriterion.Builder newBuilder() {
    return new graphene.model.idl.G_SortCriterion.Builder();
  }
  
  /** Creates a new G_SortCriterion RecordBuilder by copying an existing Builder */
  public static graphene.model.idl.G_SortCriterion.Builder newBuilder(graphene.model.idl.G_SortCriterion.Builder other) {
    return new graphene.model.idl.G_SortCriterion.Builder(other);
  }
  
  /** Creates a new G_SortCriterion RecordBuilder by copying an existing G_SortCriterion instance */
  public static graphene.model.idl.G_SortCriterion.Builder newBuilder(graphene.model.idl.G_SortCriterion other) {
    return new graphene.model.idl.G_SortCriterion.Builder(other);
  }
  
  /**
   * RecordBuilder for G_SortCriterion instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<G_SortCriterion>
    implements org.apache.avro.data.RecordBuilder<G_SortCriterion> {

    private graphene.model.idl.G_SortOrder sortDirection;
    private java.lang.String propertyName;

    /** Creates a new Builder */
    private Builder() {
      super(graphene.model.idl.G_SortCriterion.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(graphene.model.idl.G_SortCriterion.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.sortDirection)) {
        this.sortDirection = data().deepCopy(fields()[0].schema(), other.sortDirection);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.propertyName)) {
        this.propertyName = data().deepCopy(fields()[1].schema(), other.propertyName);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing G_SortCriterion instance */
    private Builder(graphene.model.idl.G_SortCriterion other) {
            super(graphene.model.idl.G_SortCriterion.SCHEMA$);
      if (isValidValue(fields()[0], other.sortDirection)) {
        this.sortDirection = data().deepCopy(fields()[0].schema(), other.sortDirection);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.propertyName)) {
        this.propertyName = data().deepCopy(fields()[1].schema(), other.propertyName);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'sortDirection' field */
    public graphene.model.idl.G_SortOrder getSortDirection() {
      return sortDirection;
    }
    
    /** Sets the value of the 'sortDirection' field */
    public graphene.model.idl.G_SortCriterion.Builder setSortDirection(graphene.model.idl.G_SortOrder value) {
      validate(fields()[0], value);
      this.sortDirection = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'sortDirection' field has been set */
    public boolean hasSortDirection() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'sortDirection' field */
    public graphene.model.idl.G_SortCriterion.Builder clearSortDirection() {
      sortDirection = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'propertyName' field */
    public java.lang.String getPropertyName() {
      return propertyName;
    }
    
    /** Sets the value of the 'propertyName' field */
    public graphene.model.idl.G_SortCriterion.Builder setPropertyName(java.lang.String value) {
      validate(fields()[1], value);
      this.propertyName = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'propertyName' field has been set */
    public boolean hasPropertyName() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'propertyName' field */
    public graphene.model.idl.G_SortCriterion.Builder clearPropertyName() {
      propertyName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public G_SortCriterion build() {
      try {
        G_SortCriterion record = new G_SortCriterion();
        record.sortDirection = fieldSetFlags()[0] ? this.sortDirection : (graphene.model.idl.G_SortOrder) defaultValue(fields()[0]);
        record.propertyName = fieldSetFlags()[1] ? this.propertyName : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
