/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package graphene.model.idl;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum G_UserInterfaceMode { 
  DOMAIN_EXPERT, TECHNICAL_EXPERT  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"G_UserInterfaceMode\",\"namespace\":\"graphene.model.idl\",\"symbols\":[\"DOMAIN_EXPERT\",\"TECHNICAL_EXPERT\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
