/*
 *
 *  Licensed to the Apache Software Foundation (ASF) under one
 *  or more contributor license agreements.  See the NOTICE file
 *  distributed with this work for additional information
 *  regarding copyright ownership.  The ASF licenses this file
 *  to you under the Apache License, Version 2.0 (the
 *  "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at
 *       http://www.apache.org/licenses/LICENSE-2.0
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */

/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package graphene.model.idl;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class G_UserLoginEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"G_UserLoginEvent\",\"namespace\":\"graphene.model.idl\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"default\":null},{\"name\":\"timeInitiated\",\"type\":\"long\"},{\"name\":\"userId\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"],\"default\":\"None\"},{\"name\":\"userName\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"],\"default\":\"None\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
   private java.lang.String id;
   private long timeInitiated;
   private java.lang.String userId;
   private java.lang.String userName;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public G_UserLoginEvent() {}

  /**
   * All-args constructor.
   */
  public G_UserLoginEvent(java.lang.String id, java.lang.Long timeInitiated, java.lang.String userId, java.lang.String userName) {
    this.id = id;
    this.timeInitiated = timeInitiated;
    this.userId = userId;
    this.userName = userName;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return timeInitiated;
    case 2: return userId;
    case 3: return userName;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.String)value$; break;
    case 1: timeInitiated = (java.lang.Long)value$; break;
    case 2: userId = (java.lang.String)value$; break;
    case 3: userName = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'timeInitiated' field.
   */
  public java.lang.Long getTimeInitiated() {
    return timeInitiated;
  }

  /**
   * Sets the value of the 'timeInitiated' field.
   * @param value the value to set.
   */
  public void setTimeInitiated(java.lang.Long value) {
    this.timeInitiated = value;
  }

  /**
   * Gets the value of the 'userId' field.
   */
  public java.lang.String getUserId() {
    return userId;
  }

  /**
   * Sets the value of the 'userId' field.
   * @param value the value to set.
   */
  public void setUserId(java.lang.String value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'userName' field.
   */
  public java.lang.String getUserName() {
    return userName;
  }

  /**
   * Sets the value of the 'userName' field.
   * @param value the value to set.
   */
  public void setUserName(java.lang.String value) {
    this.userName = value;
  }

  /** Creates a new G_UserLoginEvent RecordBuilder */
  public static graphene.model.idl.G_UserLoginEvent.Builder newBuilder() {
    return new graphene.model.idl.G_UserLoginEvent.Builder();
  }
  
  /** Creates a new G_UserLoginEvent RecordBuilder by copying an existing Builder */
  public static graphene.model.idl.G_UserLoginEvent.Builder newBuilder(graphene.model.idl.G_UserLoginEvent.Builder other) {
    return new graphene.model.idl.G_UserLoginEvent.Builder(other);
  }
  
  /** Creates a new G_UserLoginEvent RecordBuilder by copying an existing G_UserLoginEvent instance */
  public static graphene.model.idl.G_UserLoginEvent.Builder newBuilder(graphene.model.idl.G_UserLoginEvent other) {
    return new graphene.model.idl.G_UserLoginEvent.Builder(other);
  }
  
  /**
   * RecordBuilder for G_UserLoginEvent instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<G_UserLoginEvent>
    implements org.apache.avro.data.RecordBuilder<G_UserLoginEvent> {

    private java.lang.String id;
    private long timeInitiated;
    private java.lang.String userId;
    private java.lang.String userName;

    /** Creates a new Builder */
    private Builder() {
      super(graphene.model.idl.G_UserLoginEvent.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(graphene.model.idl.G_UserLoginEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeInitiated)) {
        this.timeInitiated = data().deepCopy(fields()[1].schema(), other.timeInitiated);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.userId)) {
        this.userId = data().deepCopy(fields()[2].schema(), other.userId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.userName)) {
        this.userName = data().deepCopy(fields()[3].schema(), other.userName);
        fieldSetFlags()[3] = true;
      }
    }
    
    /** Creates a Builder by copying an existing G_UserLoginEvent instance */
    private Builder(graphene.model.idl.G_UserLoginEvent other) {
            super(graphene.model.idl.G_UserLoginEvent.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeInitiated)) {
        this.timeInitiated = data().deepCopy(fields()[1].schema(), other.timeInitiated);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.userId)) {
        this.userId = data().deepCopy(fields()[2].schema(), other.userId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.userName)) {
        this.userName = data().deepCopy(fields()[3].schema(), other.userName);
        fieldSetFlags()[3] = true;
      }
    }

    /** Gets the value of the 'id' field */
    public java.lang.String getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public graphene.model.idl.G_UserLoginEvent.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'id' field */
    public graphene.model.idl.G_UserLoginEvent.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'timeInitiated' field */
    public java.lang.Long getTimeInitiated() {
      return timeInitiated;
    }
    
    /** Sets the value of the 'timeInitiated' field */
    public graphene.model.idl.G_UserLoginEvent.Builder setTimeInitiated(long value) {
      validate(fields()[1], value);
      this.timeInitiated = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'timeInitiated' field has been set */
    public boolean hasTimeInitiated() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'timeInitiated' field */
    public graphene.model.idl.G_UserLoginEvent.Builder clearTimeInitiated() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'userId' field */
    public java.lang.String getUserId() {
      return userId;
    }
    
    /** Sets the value of the 'userId' field */
    public graphene.model.idl.G_UserLoginEvent.Builder setUserId(java.lang.String value) {
      validate(fields()[2], value);
      this.userId = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'userId' field has been set */
    public boolean hasUserId() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'userId' field */
    public graphene.model.idl.G_UserLoginEvent.Builder clearUserId() {
      userId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'userName' field */
    public java.lang.String getUserName() {
      return userName;
    }
    
    /** Sets the value of the 'userName' field */
    public graphene.model.idl.G_UserLoginEvent.Builder setUserName(java.lang.String value) {
      validate(fields()[3], value);
      this.userName = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'userName' field has been set */
    public boolean hasUserName() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'userName' field */
    public graphene.model.idl.G_UserLoginEvent.Builder clearUserName() {
      userName = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public G_UserLoginEvent build() {
      try {
        G_UserLoginEvent record = new G_UserLoginEvent();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.timeInitiated = fieldSetFlags()[1] ? this.timeInitiated : (java.lang.Long) defaultValue(fields()[1]);
        record.userId = fieldSetFlags()[2] ? this.userId : (java.lang.String) defaultValue(fields()[2]);
        record.userName = fieldSetFlags()[3] ? this.userName : (java.lang.String) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
