/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package graphene.model.idl;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum G_UserFields { 
  id, active, username, avatar, email, fullname, hashedpassword, lastlogin, modified, created, numberlogins  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"G_UserFields\",\"namespace\":\"graphene.model.idl\",\"symbols\":[\"id\",\"active\",\"username\",\"avatar\",\"email\",\"fullname\",\"hashedpassword\",\"lastlogin\",\"modified\",\"created\",\"numberlogins\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
