/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package graphene.model.idl;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum G_UserFields { 
  active, username, avatar, email, fullname, hashedpassword, lastlogin, lastmodified, accountcreated, numberlogins, provenance, uncertainty  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"G_UserFields\",\"namespace\":\"graphene.model.idl\",\"symbols\":[\"active\",\"username\",\"avatar\",\"email\",\"fullname\",\"hashedpassword\",\"lastlogin\",\"lastmodified\",\"accountcreated\",\"numberlogins\",\"provenance\",\"uncertainty\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
