/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package graphene.model.idl;  
@SuppressWarnings("all")
/** * The 21st century meaning, "conceal from unauthorized
						 * view; censor but do not destroy" */
@org.apache.avro.specific.AvroGenerated
public enum G_VisualTag { 
  CHOROPLETH, CARTOGRAM, DOT_DISTRIBUTION, PROPORTIONAL_SYMBOL, CONTOUR_MAP, DASYMETRIC, FLOW_MAP, SOM, TIME_LINE, TIME_SERIES, GANTT, STREAM_GRAPH, ARC_DIAGRAM, POLAR_AREA, SANKEY, ALLUVIAL, PIE_CHART, HISTOGRAM, TAG_CLOUD, BUBBLE_CHART, BAR_CHART, TREE_MAP, SCATTER_PLOT, LINE_CHART, STEP_CHART, AREA_CHART, HEAT_MAP, SPIDER_CHART, CANDLESTICK, TREE_REGULAR, TREE_RADIAL, TREE_HYPERBOLIC, RADIAL_HIERARCHY, MATRIX, NODE_LINK_DIAGRAM, NODE_LINK_DIAGRAM3D, CIRCULAR_HIERARCHY, HIVE_PLOT, SUBWAY_MAP, DEFAULT, HIDDEN, IMAGE, VIDEO, INFINITE_SCROLL, LIST, PLUGIN, REDACTED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"G_VisualTag\",\"namespace\":\"graphene.model.idl\",\"doc\":\"* The 21st century meaning, \\\"conceal from unauthorized\\n\\t\\t\\t\\t\\t\\t * view; censor but do not destroy\\\"\",\"symbols\":[\"CHOROPLETH\",\"CARTOGRAM\",\"DOT_DISTRIBUTION\",\"PROPORTIONAL_SYMBOL\",\"CONTOUR_MAP\",\"DASYMETRIC\",\"FLOW_MAP\",\"SOM\",\"TIME_LINE\",\"TIME_SERIES\",\"GANTT\",\"STREAM_GRAPH\",\"ARC_DIAGRAM\",\"POLAR_AREA\",\"SANKEY\",\"ALLUVIAL\",\"PIE_CHART\",\"HISTOGRAM\",\"TAG_CLOUD\",\"BUBBLE_CHART\",\"BAR_CHART\",\"TREE_MAP\",\"SCATTER_PLOT\",\"LINE_CHART\",\"STEP_CHART\",\"AREA_CHART\",\"HEAT_MAP\",\"SPIDER_CHART\",\"CANDLESTICK\",\"TREE_REGULAR\",\"TREE_RADIAL\",\"TREE_HYPERBOLIC\",\"RADIAL_HIERARCHY\",\"MATRIX\",\"NODE_LINK_DIAGRAM\",\"NODE_LINK_DIAGRAM3D\",\"CIRCULAR_HIERARCHY\",\"HIVE_PLOT\",\"SUBWAY_MAP\",\"DEFAULT\",\"HIDDEN\",\"IMAGE\",\"VIDEO\",\"INFINITE_SCROLL\",\"LIST\",\"PLUGIN\",\"REDACTED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
