/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package graphene.model.idl;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum G_WorkspaceFields { 
  active, json, queries, datamap, description, title, id, modified, created  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"G_WorkspaceFields\",\"namespace\":\"graphene.model.idl\",\"symbols\":[\"active\",\"json\",\"queries\",\"datamap\",\"description\",\"title\",\"id\",\"modified\",\"created\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
