package graphene.ingest.neo4j;

public enum G_CanonicalIndexNames {
	UNIQUE_BUSINESS_PROPERTY,
	UNIQUE_FINANCIAL_PROPERTY,
	UNIQUE_COMMUNICATION_PROPERTY,
	UNIQUE_PHYSICAL_PROPERTY,
	UNIQUE_EVENT,
	UNIQUE_PARTICIPANT,
	UNIQUE_GOVERNMENT_PROPERTY,
	UNIQUE_LOCATION_PROPERTY,
	NAME,
	UNIQUE_GLOBAL_ID

}
